pos_design_patterns_exercise-mysql:
  container_name: pos_design_patterns_exercise-mysql
  image: mysql:5.7.9
  # volumes:
  #   - ~/volumes/jhipster/POS_Design_Patterns_Exercise/mysql/:/var/lib/mysql/
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=pos_design_patterns_exercise
  ports:
    - "3306:3306"
  command: mysqld --lower_case_table_names=1
